<?php
return array(
    'hutao' => '胡桃互娱',
    'yyb' => '应用宝',
    'huawei' => '华为',
    'xiaomi' => '小米',
    '360' => '360',
    'oppo' => 'oppo',
    'vivo' => 'vivo',
    'meizu' => '魅族',
    'jinli' => '金立',
    'jiuyou' => '九游',
    'kupai' => '酷派',
    'lenovo' => '联想',
    '4399' => '4399',
    'ttyy' => 'TT语音',
    'aqy' => '爱奇艺',
    'landie' => '蓝叠',
    'meitu' => '美图',
    'yeshen' => '夜神',
    'unionpay' => '银联',
    'xiantu' => '闲兔',
    'tyy' => '天宇游',
    'yinan' => '壹楠',
    'qucik' => 'qucik',
    'manbu' => '漫布',
    'hetun' => '河豚',
);